### ISSUE TITLE
US-1: Process Offerings

### ISSUE THREAD

**Issue by kokkuri3** [kokkuri3/SOEN342#2]
As an administrator, I want to make offerings available.
As an instructor I want to select lessons.
As the public, I want to view offerings.

### Tasks

- [x]  UML Domain Model [+ Package Diagram]
- [x] System sequence diagram(s) to capture success and failure scenarios
- [x] Identification of system operations and operation contracts
- [x] UML interaction diagrams
- [x] UML class diagram
- [x] Implementation
