### ISSUE TITLE
US-2: Process Bookings

### ISSUE THREAD

**Issue by kokkuri3** [kokkuri3/SOEN342#3]
As a client, I want to be able to sign up to offerings available to me.

### Tasks

- [x] Client UML sequence diagram
- [x] Update Main.java with Client and Booking
- [x] Update operation contracts with Client methods
- [x] System sequence diagram for startMakeNewBooking()
- [x] Update UML class diagram
